<script type="text/javascript" src="/resources/scripts/external/jQuery/jquery-2.1.1.js"></script>
<script type="text/javascript" src="/resources/scripts/external/bootstrap-3.3.2/js/bootstrap.js"></script>
<script type="text/javascript" src="/resources/scripts/external/angular-1.3.8/angular.js"></script>
<script type="text/javascript" src="/resources/scripts/external/angular-1.3.8/angular-route.js"></script>
<script type="text/javascript" src="/resources/scripts/external/angular-1.3.8/angular-resource.min.js"></script>
<script type="text/javascript" src="/resources/scripts/external/bootbox/bootbox.js"></script>
<script type="text/javascript" src="/resources/scripts/external/angular-pagination/dirPagination.js"></script>
<script type="text/javascript" src="/resources/scripts/internal/angularjs/common/app/app.js"></script>
<script type="text/javascript" src="/resources/scripts/internal/angularjs/common/controllers/common-controllers.js"></script>
<script type="text/javascript" src="/resources/scripts/internal/angularjs/common/directives/common-directive.js"></script>
<script type="text/javascript" src="/resources/scripts/internal/angularjs/common/filters/common-filter.js"></script>
<script type="text/javascript" src="/resources/scripts/internal/angularjs/common/services/common-services.js"></script>